### ISSUE TITLE
'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by philippfreyer** [knifecake/steady-queue#26]
Good morning @knifecake 
there seems to be an issue with the process of an execution not always being set:

```
2026-02-11 06:03:30,907 - django.tasks - INFO - Task id=38884 path=dip_update_signals.tasks.process_update_signal state=SUCCESSFUL
NoneType: None
2026-02-11 06:03:30,908 - steady_queue - ERROR - error in AppExecutor: 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python3.14/site-packages/steady_queue/app_executor.py", line 33, in wrap_in_app_executor
    yield
  File "/usr/local/lib/python3.14/site-packages/steady_queue/processes/pool.py", line 33, in wrapped_execution
    "worker": execution.process.name,
              ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
2026-02-11 06:03:30,927 - steady_queue - INFO - worker-bad8ed2f8c231bb5d8e6 claimed job 38886 dip_update_signals.tasks.process_update_signal
2026-02-11 06:03:30,943 - django.tasks - INFO - Task id=38883 path=dip_update_signals.tasks.process_update_signal state=SUCCESSFUL
NoneType: None
2026-02-11 06:03:30,943 - steady_queue - ERROR - error in AppExecutor: 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python3.14/site-packages/steady_queue/app_executor.py", line 33, in wrap_in_app_executor
    yield
  File "/usr/local/lib/python3.14/site-packages/steady_queue/processes/pool.py", line 33, in wrapped_execution
    "worker": execution.process.name,
              ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
2026-02-11 06:03:30,946 - django.tasks - INFO - Task id=38886 path=dip_update_signals.tasks.process_update_signal state=RUNNING
```

**Comment by philippfreyer** [comment]
Ans most likely related as well:
```
2026-02-11 06:03:34,621 - steady_queue - ERROR - error in AppExecutor: 'NoneType' object has no attribute 'heartbeat'
Traceback (most recent call last):
  File "/usr/local/lib/python3.14/site-packages/steady_queue/app_executor.py", line 33, in wrap_in_app_executor
    yield
  File "/usr/local/lib/python3.14/site-packages/steady_queue/processes/registrable.py", line 74, in heartbeat
    self.process.heartbeat()
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'heartbeat'
2026-02-11 06:03:34,624 - steady_queue - ERROR - unhandled exception in timer task: 'NoneType' object has no attribute 'heartbeat'
Traceback (most recent call last):
  File "/usr/local/lib/python3.14/site-packages/steady_queue/processes/timer.py", line 78, in wrapped_callable
    self.callable()
    ~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.14/site-packages/steady_queue/processes/registrable.py", line 60, in <lambda>
    callable=lambda: self.heartbeat(),
                     ~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.14/site-packages/steady_queue/processes/registrable.py", line 74, in heartbeat
    self.process.heartbeat()
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'heartbeat'
```

**Comment by philippfreyer** [comment]
This is my steady queue configuration, in case this helps:
```
TASKS = {
    "default": {
        "BACKEND": "steady_queue.backend.SteadyQueueBackend",
        "QUEUES": ["default", "certificates"],
        "OPTIONS": {},
    }
}
STEADY_QUEUE = Configuration.Options(
    dispatchers=[
        Configuration.Dispatcher(
            polling_interval=timedelta(seconds=1),
            batch_size=500
        )
    ],
    workers=[
        Configuration.Worker(
            queues=["certificates"],
            threads=3,
            polling_interval=timedelta(seconds=0.1)
        ),
        Configuration.Worker(
            queues=["default"],
            threads=3,
            polling_interval=timedelta(seconds=0.1)
        ),
        Configuration.Worker(
            queues=["*"],
            threads=4,
            processes=2,
            polling_interval=timedelta(seconds=0.1)
        ),
        Configuration.Worker(
            queues=["*"],
            threads=4,
            processes=2,
            polling_interval=timedelta(seconds=0.1)
        ),
    ]
)
```

**Comment by knifecake** [comment]
Like with #25, i'm not 100% sure the fixes we introduced in #38 actually did anything but i've added more coverage via #55. If you notice it again, pls reopen and we'll investigate more!!
